reference to 'perfetto_track_event' is ambiguous
- use ::perfetto_track_event instead of perfetto_track_event or
  variables
- fixes following errors:

error: reference to 'perfetto_track_event' is ambiguous
  128 |     TRACE_EVENT_BEGIN(_category(), perfetto::StaticString(_label),
      |     ^
/rocm_sdk_builder_612/builddir/timemory/external/perfetto/sdk/perfetto.h:20246:3: note: expanded from macro 'TRACE_EVENT_BEGIN'
 20246 |   PERFETTO_INTERNAL_TRACK_EVENT_WITH_METHOD(   \
       |   ^
/rocm_sdk_builder_612/builddir/timemory/external/perfetto/sdk/perfetto.h:19754:9: note: expanded from macro 'PERFETTO_INTERNAL_TRACK_EVENT_WITH_METHOD'
 19754 |         PERFETTO_GET_CATEGORY_INDEX(category);                                 \
       |         ^
/rocm_sdk_builder_612/builddir/timemory/external/perfetto/sdk/perfetto.h:19735:3: note: expanded from macro 'PERFETTO_GET_CATEGORY_INDEX'
 19735 |   PERFETTO_TRACK_EVENT_NAMESPACE::internal::kConstExprCategoryRegistry.Find( \
       |   ^
/rocm_sdk_builder_612/builddir/timemory/external/perfetto/sdk/perfetto.h:20020:40: note: expanded from macro 'PERFETTO_TRACK_EVENT_NAMESPACE'
 20020 | #define PERFETTO_TRACK_EVENT_NAMESPACE perfetto_track_event
       |                                        ^
/rocm_sdk_builder_612/src_projects/timemory/source/timemory/components/perfetto/backends.hpp:57:1: note: candidate found by name lookup is 'perfetto_track_event'
   57 | PERFETTO_DEFINE_CATEGORIES(TIMEMORY_PERFETTO_CATEGORIES);
      | ^
/rocm_sdk_builder_612/builddir/timemory/external/perfetto/sdk/perfetto.h:20120:3: note: expanded from macro 'PERFETTO_DEFINE_CATEGORIES'
 20120 |   PERFETTO_USE_CATEGORIES_FROM_NAMESPACE(perfetto)
       |   ^
/rocm_sdk_builder_612/builddir/timemory/external/perfetto/sdk/perfetto.h:20099:13: note: expanded from macro 'PERFETTO_USE_CATEGORIES_FROM_NAMESPACE'
 20099 |   namespace PERFETTO_TRACK_EVENT_NAMESPACE {                               \
       |             ^
/rocm_sdk_builder_612/builddir/timemory/external/perfetto/sdk/perfetto.h:20020:40: note: expanded from macro 'PERFETTO_TRACK_EVENT_NAMESPACE'
 20020 | #define PERFETTO_TRACK_EVENT_NAMESPACE perfetto_track_event
       |                                        ^
/rocm_sdk_builder_612/src_projects/timemory/source/timemory/components/perfetto/backends.hpp:57:1: note: candidate found by name lookup is 'perfetto::perfetto_track_event'
/rocm_sdk_builder_612/builddir/timemory/external/perfetto/sdk/perfetto.h:20119:3: note: expanded from macro 'PERFETTO_DEFINE_CATEGORIES'
 20119 |   PERFETTO_DEFINE_CATEGORIES_IN_NAMESPACE(perfetto, __VA_ARGS__); \
       |   ^
/rocm_sdk_builder_612/builddir/timemory/external/perfetto/sdk/perfetto.h:20092:3: note: expanded from macro 'PERFETTO_DEFINE_CATEGORIES_IN_NAMESPACE'
 20092 |   PERFETTO_DEFINE_CATEGORIES_IN_NAMESPACE_WITH_ATTRS(    \
       |   ^
/rocm_sdk_builder_612/builddir/timemory/external/perfetto/sdk/perfetto.h:20076:13: note: expanded from macro 'PERFETTO_DEFINE_CATEGORIES_IN_NAMESPACE_WITH_ATTRS'
 20076 |   namespace PERFETTO_TRACK_EVENT_NAMESPACE {                               \
       |             ^
/rocm_sdk_builder_612/builddir/timemory/external/perfetto/sdk/perfetto.h:20020:40: note: expanded from macro 'PERFETTO_TRACK_EVENT_NAMESPACE'
 20020 | #define PERFETTO_TRACK_EVENT_NAMESPACE perfetto_track_event
       |                                        ^
In file included from /rocm_sdk_builder_612/src_projects/timemory/source/tools/timemory-avail/timemory-avail.cpp:27:
In file included from /rocm_sdk_builder_612/src_projects/timemory/source/timemory/components.hpp:150:
In file included from /rocm_sdk_builder_612/src_projects/timemory/source/timemory/components/perfetto/perfetto.hpp:28:
/rocm_sdk_builder_612/src_projects/timemory/source/timemory/components/perfetto/backends.hpp:128:5: error: use of undeclared identifier 'tns'; did you mean 'tms'?
  128 |     TRACE_EVENT_BEGIN(_category(), perfetto::StaticString(_label),
      |     ^
/rocm_sdk_builder_612/builddir/timemory/external/perfetto/sdk/perfetto.h:20246:3: note: expanded from macro 'TRACE_EVENT_BEGIN'
 20246 |   PERFETTO_INTERNAL_TRACK_EVENT_WITH_METHOD(   \
       |   ^
/rocm_sdk_builder_612/builddir/timemory/external/perfetto/sdk/perfetto.h:19757:7: note: expanded from macro 'PERFETTO_INTERNAL_TRACK_EVENT_WITH_METHOD'
 19757 |       tns::TrackEvent::CallIfEnabled(                                          \
       |       ^
/usr/include/sys/times.h:32:8: note: 'tms' declared here
   32 | struct tms
      |        ^
In file included from /rocm_sdk_builder_612/src_projects/timemory/source/tools/timemory-avail/timemory-avail.cpp:27:
In file included from /rocm_sdk_builder_612/src_projects/timemory/source/timemory/components.hpp:150:
In file included from /rocm_sdk_builder_612/src_projects/timemory/source/timemory/components/perfetto/perfetto.hpp:28:
/rocm_sdk_builder_612/src_projects/timemory/source/timemory/components/perfetto/backends.hpp:128:5: error: no member named 'TrackEvent' in 'tms'; did you mean simply 'TrackEvent'?
  128 |     TRACE_EVENT_BEGIN(_category(), perfetto::StaticString(_label),
      |     ^
/rocm_sdk_builder_612/builddir/timemory/external/perfetto/sdk/perfetto.h:20246:3: note: expanded from macro 'TRACE_EVENT_BEGIN'
 20246 |   PERFETTO_INTERNAL_TRACK_EVENT_WITH_METHOD(   \
       |   ^
/rocm_sdk_builder_612/builddir/timemory/external/perfetto/sdk/perfetto.h:19757:7: note: expanded from macro 'PERFETTO_INTERNAL_TRACK_EVENT_WITH_METHOD'
 19757 |       tns::TrackEvent::CallIfEnabled(

Signed-off-by: Mika Laitio <lamikr@gmail.com>